
  CREATE TABLE "BASIC"."SF_ACTION"
   (	"APP_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"CODE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"SOURCE_CODE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"TARGET_CODE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"FLAG" VARCHAR2(1 BYTE) DEFAULT '1',
	 CONSTRAINT "SF_ACTION_PK" PRIMARY KEY ("APP_ID", "CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BASIC"  ENABLE,
	 CONSTRAINT "SF_ACTION_SF_STATE_FK1" FOREIGN KEY ("APP_ID", "SOURCE_CODE")
	  REFERENCES "BASIC"."SF_STATE" ("APP_ID", "CODE") ENABLE,
	 CONSTRAINT "SF_ACTION_SF_STATE_FK2" FOREIGN KEY ("APP_ID", "TARGET_CODE")
	  REFERENCES "BASIC"."SF_STATE" ("APP_ID", "CODE") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BASIC" ;


   COMMENT ON COLUMN "BASIC"."SF_ACTION"."APP_ID" IS '模块编码';

   COMMENT ON COLUMN "BASIC"."SF_ACTION"."CODE" IS '动作编号';

   COMMENT ON COLUMN "BASIC"."SF_ACTION"."NAME" IS '动作名';

   COMMENT ON COLUMN "BASIC"."SF_ACTION"."SOURCE_CODE" IS '源状态 编码';

   COMMENT ON COLUMN "BASIC"."SF_ACTION"."TARGET_CODE" IS '目标状态 编码';

   COMMENT ON COLUMN "BASIC"."SF_ACTION"."FLAG" IS '标识';

   COMMENT ON TABLE "BASIC"."SF_ACTION"  IS '动作';
