
  CREATE TABLE "BASIC"."SF_BUSINESS_PROCESS"
   (	"APP_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"BUSINESS_CODE" VARCHAR2(500 BYTE) NOT NULL ENABLE,
	"STATE_CODE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	 CONSTRAINT "SF_BUSINESS_PROCESS_PK" PRIMARY KEY ("APP_ID", "BUSINESS_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BASIC"  ENABLE,
	 CONSTRAINT "SF_BUZ_PROC_SF_STATE_FK" FOREIGN KEY ("APP_ID", "STATE_CODE")
	  REFERENCES "BASIC"."SF_STATE" ("APP_ID", "CODE") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BASIC" ;


   COMMENT ON COLUMN "BASIC"."SF_BUSINESS_PROCESS"."APP_ID" IS '模块编码';

   COMMENT ON COLUMN "BASIC"."SF_BUSINESS_PROCESS"."BUSINESS_CODE" IS '业务唯一码';

   COMMENT ON COLUMN "BASIC"."SF_BUSINESS_PROCESS"."STATE_CODE" IS '状态编号';

   COMMENT ON TABLE "BASIC"."SF_BUSINESS_PROCESS"  IS '业务过程当前状态';

