
  CREATE TABLE "BASIC"."SF_STATE"
   (	"APP_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"CODE" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
	"FLAG" VARCHAR2(1 BYTE) DEFAULT '1',
	 CONSTRAINT "SF_STATE_PK" PRIMARY KEY ("APP_ID", "CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BASIC"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BASIC" ;


   COMMENT ON COLUMN "BASIC"."SF_STATE"."APP_ID" IS '模块编码';

   COMMENT ON COLUMN "BASIC"."SF_STATE"."CODE" IS '状态编号';

   COMMENT ON COLUMN "BASIC"."SF_STATE"."NAME" IS '状态名';

   COMMENT ON COLUMN "BASIC"."SF_STATE"."FLAG" IS '标识';

   COMMENT ON TABLE "BASIC"."SF_STATE"  IS '状态';

