server:
  port: 5015
  servlet:
    session:
      timeout: 50400s


#热部署生效
spring:
  devtools:
    restart:
      enabled: true
      #设置重启的目录
      additional-paths: src/main/java
  session:
    #指定session type，none / redis
    store-type: none

sf:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/portal?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    validation-query: select 1 from dual #指定获取连接时连接校验的sql查询语句
    test-on-borrow: true #当从连接池借用连接时，是否测试该连接.
    test-on-connect: true #创建时，是否测试连接
    test-while-idle: true #当连接空闲时，是否执行连接测试.
    time-between-eviction-runs-millis: 60000 #指定空闲连接检查、废弃连接清理、空闲连接池大小调整之间的操作时间间隔


logging:
  level:
    root: INFO
    com.chivalry.repository.mapper: INFO
  path: /logs/sf/

